<?php
/**
 * Copyright © Magento2Express. All rights reserved.
 * @author: <mailto:contact@magento2express.com>.
 */

use Magento\Framework\App\Action\Action;
?>
<?php
$configHelper = $block->getModuleConfig();
$cartPosition = $configHelper->getCartPosition();
$infoPosition = $configHelper->getConfigByScope('m2express_home2steps/general/info_position');
$filterAttributes = $configHelper->getConfigByScope('m2express_home2steps/general/filter_attributes');
$filterAttributesArr = explode(',', $filterAttributes);
$themeStyle = $configHelper->getThemeStyle();

$showWishlist = false;
$showCompare = true;
$showCart = true;

$type = 'widget-new-grid';
$viewMode = 'grid';
$image = 'category_page_grid';

$pos = $block->getPositioned();

?>
<div id="custom-main-container">
    <div id="test-grid" class="owl-carousel">
        <?php if (($_products = $block->getProductCollection()) && $_products->getSize()): ?>
            <?php $suffix = $block->getNameInLayout(); ?>
            <?php foreach ($_products->getItems() as $_product): ?>
                <?php
                $attributes = $_product->getCustomAttributes();
                $filterDataClassVariable = '';
                $noListedArr = ['description','image','small_image','thumbnail'];
                foreach ($attributes as $attribute) {
                    if (!in_array($attribute->getAttributeCode(), $noListedArr)) {
                        $allFilterable = explode(",", $attribute->getValue());
                        foreach ($allFilterable as $value) {
                            $filterDataClassVariable .= " ".$attribute->getAttributeCode()."-".$value;
                        }
                    }
                }

                ?>
                <div data-container="product-grid" class="item <?=$filterDataClassVariable; ?>" >
                    <div class="custom-product-container custom-info-pos-<?=$infoPosition;?>">
                        <div style="position: relative; background: url('<?= $block->getImage($_product, 'product_page_image_large')->getImageUrl() ?>');">
                            <div class="right-column">
                                <!-- Product Description -->
                                <div class="custom-product-description">
                                    <h1><?= /* @escapeNotVerified */ $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                                    <p><?= /* @escapeNotVerified */ $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getDescription(), 'description') ?></p>
                                </div>
                                <div class="custom-product-options">
                                    <?php echo $block->getProductDetailsHtml($_product); ?>
                                </div>
                                <!-- Product Pricing -->
                                <div class="custom-product-price">
                                    <?php echo $this->getProductPricetoHtml($_product, $type); ?>
                                </div>
                            </div>
                            <div class="home-product-button-list">
                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions">
                                        <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                            <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <?php if($_product->getTypeId() == \Magento\GroupedProduct\Model\Product\Type\Grouped::TYPE_CODE): ?>
                                                    <div style="display: none;" class="cart-popup-<?= $_product->getId(); ?>">
                                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                            <?= $block->getBlockHtml('formkey') ?>
                                                        <?php $associatedProducts = $_product->getTypeInstance()->getAssociatedProducts($_product); ?>
                                                        <table class="table data grouped" id="super-product-table">
                                                            <caption class="table-caption"><?= /* @escapeNotVerified */ __('Grouped product items') ?></caption>
                                                            <thead>
                                                            <tr>
                                                                <th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Product Name') ?></th>
                                                                <?php if ($_product->isSaleable()): ?>
                                                                    <th class="col qty" scope="col"><?= /* @escapeNotVerified */ __('Qty') ?></th>
                                                                <?php endif; ?>
                                                            </tr>
                                                            </thead>
                                                                <?php foreach ($associatedProducts as $_item): ?>
                                                                    <tbody>
                                                                    <tr>
                                                                        <td data-th="<?= $block->escapeHtml(__('Product Name')) ?>" class="col item">
                                                                            <strong class="product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
                                                                            <?php if ($block->getCanShowProductPrice($_product)): ?>
                                                                                <?php if ($block->getCanShowProductPrice($_item)): ?>
                                                                                    <?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>
                                                                                <?php endif; ?>
                                                                            <?php endif; ?>
                                                                        </td>
                                                                        <?php if ($_product->isSaleable()): ?>
                                                                            <td data-th="<?= $block->escapeHtml(__('Qty')) ?>" class="col qty">
                                                                                <?php if ($_item->isSaleable()) : ?>
                                                                                    <div class="control qty">
                                                                                        <input type="number"
                                                                                               name="super_group[<?= /* @escapeNotVerified */ $_item->getId() ?>]"
                                                                                               data-selector="super_group[<?= /* @escapeNotVerified */ $_item->getId() ?>]"
                                                                                               value="<?= /* @escapeNotVerified */ $_item->getQty() * 1 ?>"
                                                                                               title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                                                                                               class="input-text qty"
                                                                                               data-validate="{'validate-grouped-qty':'#super-product-table'}"
                                                                                               data-errors-message-box="#validation-message-box"/>
                                                                                    </div>
                                                                                <?php else: ?>
                                                                                    <div class="stock unavailable" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
                                                                                        <span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
                                                                                    </div>
                                                                                <?php endif; ?>
                                                                            </td>
                                                                        <?php endif; ?>
                                                                    </tr>
                                                                    <?php if ($block->getCanShowProductPrice($_product)
                                                                        && $block->getCanShowProductPrice($_item)
                                                                        && trim($block->getProductPriceHtml(
                                                                            $_item,
                                                                            \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                                                                        ))): ?>
                                                                        <tr class="row-tier-price">
                                                                            <td colspan="2">
                                                                                <?= $block->getProductPriceHtml(
                                                                                    $_item,
                                                                                    \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                                                                                ) ?>
                                                                            </td>
                                                                        </tr>
                                                                    <?php endif; ?>
                                                                    </tbody>
                                                                <?php endforeach; ?>
                                                        </table>
                                                        <button type="submit"
                                                                title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                class="action tocart primary">
                                                            <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                        </button>
                                                        </form>
                                                    </div>
                                                    <button type="button" data-id="<?= $_product->getId(); ?>"
                                                            title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                            class="action opencartpopup primary">
                                                        <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                    </button>
                                                <?php elseif($_product->getTypeId() == \Magento\Bundle\Model\Product\Type::TYPE_CODE): ?>
                                                    <div style="display: none;" class="cart-popup-<?= $_product->getId(); ?>">
                                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                            <?= $block->getBlockHtml('formkey') ?>
                                                        <?php if ($optBlock = $block->getChildBlock('type_bundle_options')->setData('product', $_product)): ?>
                                                            <?= $block->getChildHtml('type_bundle_options') ?>
                                                        <?php endif; ?>
                                                        <button type="submit"
                                                                title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                class="action tocart primary">
                                                            <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                        </button>
                                                        </form>
                                                    </div>
                                                        <button type="button" data-id="<?= $_product->getId(); ?>"
                                                                title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                class="action opencartpopup primary">
                                                            <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                        </button>
                                                <?php else: ?>
                                                <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                                    <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                                    <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                        <button type="submit"
                                                                title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                class="action tocart primary">
                                                            <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                        </button>
                                                </form>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <?php if ($_product->getIsSalable()): ?>
                                                    <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
</div>

<?php
if($themeStyle=='horizontal') {
    ?>
    <script>var sliderIn = 'slideInUp', sliderOut = 'slideOutUp';</script>
    <?php
} else {
    ?>
    <script>var sliderIn = 'fadeInRight', sliderOut = 'fadeOutRight';</script>
    <?php
}
?>
<script type="text/x-magento-init">
{
    "[data-role=tocart-form], .form.map.checkout": {
        "catalogAddToCart": { }
    }
}
</script>
<script>
    requirejs([
            'jquery',
            'Magento_Ui/js/modal/modal',
            'owlCarousel'
        ],
        function($, modal, owlCarousel) {

            var owl = $('.owl-carousel');
            owl.owlCarousel({
                autoplay: true,
                items: 1,
                nav: true,
                loop: true,
                autoplayHoverPause: true,
                animateOut: sliderOut,
                animateIn: sliderIn,
                autoplayTimeout: 10000
            });

            $.fn.owlRemoveItem = function (num) {

                var owl_data = $(this).data('owl.carousel');

                owl_data._items = $.map(
                    owl_data._items,
                    function (data, index) {

                        if (index !== num) return data;
                    }
                );

                $(this).find(".owl-item").eq(num).remove();

            };

            $.fn.owlFilter = function (data, callback) {

                var owl = this,
                    $elemCopy = $('<div>').css('display', 'none');

                /* check attr owl-clone exist */

                if (typeof($(owl).data('owl-clone')) === 'undefined') {

                    $(owl).find(".owl-item:not(.cloned)").clone().appendTo($elemCopy);
                    $(owl).data('owl-clone', $elemCopy);

                }

                else {

                    $elemCopy = $(owl).data('owl-clone');

                }

                /* clear content */

                owl.trigger('replace.owl.carousel', ['<div/>']);

                switch (data) {

                    case '*':

                        $elemCopy.children().each(
                            function () {
                                owl.trigger('add.owl.carousel', [$(this).clone()]);
                            }
                        );

                        break;

                    default:

                        $elemCopy.find(data).each(
                            function () {
                                owl.trigger('add.owl.carousel', [$(this).parent().clone()]);
                            }
                        );

                        break;
                }

                /* remove item empty when clear */
                owl.owlRemoveItem(0);
                owl.trigger('refresh.owl.carousel').trigger('to.owl.carousel', [0]);

                // callback
                if (callback) callback.call(this, owl);
            };

            $(".opencartpopup").on('click',function(){
                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: false,
                    title: false,
                    buttons: [{
                        text: $.mage.__('Continue'),
                        class: 'mymodal1',
                        click: function () {
                            this.closeModal();
                        }
                    }]
                };
                var modalElement = $('.cart-popup-' + $(this).data('id'));
                var popup = modal(options, modalElement);
                modalElement.modal('openModal');
            });
        }
    );
</script>